-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE billing.credit_note_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  credit_note_id uuid NOT NULL,
  invoice_item_id uuid,
  item_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_price numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric AND tax_rate <= 100::numeric),
  line_subtotal numeric NOT NULL DEFAULT 0,
  line_tax numeric NOT NULL DEFAULT 0,
  line_total numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT credit_note_items_pkey PRIMARY KEY (id),
  CONSTRAINT credit_note_items_credit_note_id_fkey FOREIGN KEY (credit_note_id) REFERENCES billing.credit_notes(id),
  CONSTRAINT credit_note_items_invoice_item_id_fkey FOREIGN KEY (invoice_item_id) REFERENCES billing.invoice_items(id),
  CONSTRAINT credit_note_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id)
);
CREATE TABLE billing.credit_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  warehouse_id uuid,
  credit_note_number text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'issued'::text, 'void'::text])),
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  reason text,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT credit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT credit_notes_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT credit_notes_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES billing.invoices(id),
  CONSTRAINT credit_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES billing.customers(id),
  CONSTRAINT credit_notes_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES billing.warehouses(id),
  CONSTRAINT credit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  billing_address jsonb,
  tax_id text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.debit_note_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  debit_note_id uuid NOT NULL,
  purchase_bill_item_id uuid,
  item_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_cost numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric AND tax_rate <= 100::numeric),
  line_subtotal numeric NOT NULL DEFAULT 0,
  line_tax numeric NOT NULL DEFAULT 0,
  line_total numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT debit_note_items_pkey PRIMARY KEY (id),
  CONSTRAINT debit_note_items_debit_note_id_fkey FOREIGN KEY (debit_note_id) REFERENCES billing.debit_notes(id),
  CONSTRAINT debit_note_items_purchase_bill_item_id_fkey FOREIGN KEY (purchase_bill_item_id) REFERENCES billing.purchase_bill_items(id),
  CONSTRAINT debit_note_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id)
);
CREATE TABLE billing.debit_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  purchase_bill_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  warehouse_id uuid,
  debit_note_number text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'issued'::text, 'void'::text])),
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  reason text,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT debit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT debit_notes_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT debit_notes_purchase_bill_id_fkey FOREIGN KEY (purchase_bill_id) REFERENCES billing.purchase_bills(id),
  CONSTRAINT debit_notes_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES billing.vendors(id),
  CONSTRAINT debit_notes_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES billing.warehouses(id),
  CONSTRAINT debit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  item_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_price numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric AND tax_rate <= 100::numeric),
  line_subtotal numeric NOT NULL DEFAULT 0,
  line_tax numeric NOT NULL DEFAULT 0,
  line_total numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES billing.invoices(id),
  CONSTRAINT invoice_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id)
);
CREATE TABLE billing.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  warehouse_id uuid,
  offer_id uuid,
  invoice_number text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'partially_paid'::text, 'paid'::text, 'overdue'::text, 'void'::text])),
  currency text NOT NULL DEFAULT 'INR'::text,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  notes text,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  discount_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES billing.customers(id),
  CONSTRAINT invoices_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES billing.warehouses(id),
  CONSTRAINT invoices_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES billing.offers(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.item_stock (
  item_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  quantity_on_hand numeric NOT NULL DEFAULT 0,
  CONSTRAINT item_stock_pkey PRIMARY KEY (item_id, warehouse_id),
  CONSTRAINT item_stock_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id),
  CONSTRAINT item_stock_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES billing.warehouses(id)
);
CREATE TABLE billing.items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  sku text,
  description text,
  hsn_sac_code text,
  unit text NOT NULL DEFAULT 'pcs'::text,
  unit_price numeric NOT NULL DEFAULT 0,
  purchase_price numeric NOT NULL DEFAULT 0,
  tax_rate_id uuid,
  track_inventory boolean NOT NULL DEFAULT true,
  reorder_level numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT items_pkey PRIMARY KEY (id),
  CONSTRAINT items_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT items_tax_rate_id_fkey FOREIGN KEY (tax_rate_id) REFERENCES billing.tax_rates(id)
);
CREATE TABLE billing.memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'owner'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT memberships_pkey PRIMARY KEY (id),
  CONSTRAINT memberships_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE billing.offer_items (
  offer_id uuid NOT NULL,
  item_id uuid NOT NULL,
  CONSTRAINT offer_items_pkey PRIMARY KEY (offer_id, item_id),
  CONSTRAINT offer_items_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES billing.offers(id),
  CONSTRAINT offer_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id)
);
CREATE TABLE billing.offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'flat'::text])),
  value numeric NOT NULL CHECK (value >= 0::numeric),
  applies_to_all_items boolean NOT NULL DEFAULT true,
  starts_at date,
  ends_at date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT offers_pkey PRIMARY KEY (id),
  CONSTRAINT offers_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id)
);
CREATE TABLE billing.org_document_counters (
  org_id uuid NOT NULL,
  doc_type text NOT NULL CHECK (doc_type = ANY (ARRAY['invoice'::text, 'purchase_bill'::text, 'credit_note'::text, 'debit_note'::text])),
  next_value integer NOT NULL DEFAULT 1,
  CONSTRAINT org_document_counters_pkey PRIMARY KEY (org_id, doc_type),
  CONSTRAINT org_document_counters_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id)
);
CREATE TABLE billing.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  billing_email text,
  default_currency text NOT NULL DEFAULT 'INR'::text,
  invoice_prefix text NOT NULL DEFAULT 'INV'::text,
  bill_prefix text NOT NULL DEFAULT 'BILL'::text,
  credit_note_prefix text NOT NULL DEFAULT 'CN'::text,
  debit_note_prefix text NOT NULL DEFAULT 'DN'::text,
  gstin text,
  gst_registered boolean NOT NULL DEFAULT false,
  state_code text,
  pdf_watermark_text text,
  pdf_logo_url text,
  pdf_footer_notes text,
  financial_year_start_month integer NOT NULL DEFAULT 4 CHECK (financial_year_start_month >= 1 AND financial_year_start_month <= 12),
  low_stock_alerts_enabled boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE billing.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  method text NOT NULL DEFAULT 'manual'::text CHECK (method = ANY (ARRAY['manual'::text, 'bank_transfer'::text, 'cash'::text, 'upi'::text, 'razorpay'::text])),
  reference text,
  notes text,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES billing.invoices(id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.purchase_bill_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_bill_id uuid NOT NULL,
  item_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_cost numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric AND tax_rate <= 100::numeric),
  line_subtotal numeric NOT NULL DEFAULT 0,
  line_tax numeric NOT NULL DEFAULT 0,
  line_total numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_bill_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_bill_items_purchase_bill_id_fkey FOREIGN KEY (purchase_bill_id) REFERENCES billing.purchase_bills(id),
  CONSTRAINT purchase_bill_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id)
);
CREATE TABLE billing.purchase_bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  warehouse_id uuid,
  bill_number text,
  vendor_invoice_number text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'received'::text, 'partially_paid'::text, 'paid'::text, 'void'::text])),
  currency text NOT NULL DEFAULT 'INR'::text,
  bill_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  notes text,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_bills_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_bills_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT purchase_bills_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES billing.vendors(id),
  CONSTRAINT purchase_bills_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES billing.warehouses(id),
  CONSTRAINT purchase_bills_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.purchase_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  purchase_bill_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  method text NOT NULL DEFAULT 'bank_transfer'::text CHECK (method = ANY (ARRAY['bank_transfer'::text, 'cash'::text, 'upi'::text, 'cheque'::text, 'other'::text])),
  reference text,
  notes text,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_payments_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_payments_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT purchase_payments_purchase_bill_id_fkey FOREIGN KEY (purchase_bill_id) REFERENCES billing.purchase_bills(id),
  CONSTRAINT purchase_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  item_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  quantity_delta numeric NOT NULL CHECK (quantity_delta <> 0::numeric),
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['purchase'::text, 'purchase_void'::text, 'sale'::text, 'sale_void'::text, 'sales_return'::text, 'sales_return_void'::text, 'purchase_return'::text, 'purchase_return_void'::text, 'adjustment'::text])),
  reference_type text,
  reference_id uuid,
  notes text,
  created_by uuid DEFAULT uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_item_id_fkey FOREIGN KEY (item_id) REFERENCES billing.items(id),
  CONSTRAINT stock_movements_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT stock_movements_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES billing.warehouses(id),
  CONSTRAINT stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.superadmins (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT superadmins_pkey PRIMARY KEY (user_id),
  CONSTRAINT superadmins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE billing.tax_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  rate numeric NOT NULL CHECK (rate >= 0::numeric AND rate <= 100::numeric),
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tax_rates_pkey PRIMARY KEY (id),
  CONSTRAINT tax_rates_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id)
);
CREATE TABLE billing.vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  billing_address jsonb,
  tax_id text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id),
  CONSTRAINT vendors_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE billing.warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  address jsonb,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT warehouses_org_id_fkey FOREIGN KEY (org_id) REFERENCES billing.organizations(id)
);